name: Deploy Next.js Portfolio to EC2

on:
  push:
    branches:
      - main # deploy on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Archive full project
        run: tar -czf build.tar.gz --ignore-failed-read .next package.json public next.config.ts node_modules

      - name: Backup current app
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            timestamp=$(date +%Y%m%d%H%M%S)
            TARGET_DIR="${{ secrets.APP_DIR }}/portfolio"

            # Remove old backups
            rm -rf "${TARGET_DIR}_backup_"*

            # Create new backup if app exists
            if [ -d "$TARGET_DIR" ]; then
              mv "$TARGET_DIR" "${TARGET_DIR}_backup_$timestamp"
            fi

      - name: Copy build file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build.tar.gz"
          target: "${{ secrets.APP_DIR }}"

      - name: Extract build to portfolio on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            TARGET_DIR="${{ secrets.APP_DIR }}/portfolio"
            mkdir -p "$TARGET_DIR"
            tar -xzf ${{ secrets.APP_DIR }}/build.tar.gz -C "$TARGET_DIR"
            rm ${{ secrets.APP_DIR }}/build.tar.gz

      - name: Restart app on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ${{ secrets.APP_DIR }}/portfolio
            yarn
            pm2 restart 0 || pm2 start npm --name "next-app" -- start
